name: Check for AI robots.txt update

on:
  workflow_dispatch:
  schedule:
    - cron:  '12 5 * * *'

jobs:
  get-robots-version:
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.robots-check.outputs.modified }}
      version: ${{ steps.robots-check.outputs.version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Fetch robots version
        id: robots-check
        run: |
          ROBOTS_VERSION=$(curl -sL https://api.github.com/repos/ai-robots-txt/ai.robots.txt/releases/latest | jq -r .tag_name)
          FILE_VERSION=$(grep -Poe '# Version: \K(v\d+.\d+)' ./layouts/robots.txt)
          if [[ ROBOTS_VERSION == FILE_VERSION ]]; then
              echo "modified=false" >> $GITHUB_OUTPUT
          else
              echo "**** New AI robots.txt version ${ROBOTS_VERSION} available"
              echo "modified=true" >> $GITHUB_OUTPUT
              echo "version=${ROBOTS_VERSION}" >> $GITHUB_OUTPUT
          fi

  update-robots-version:
    runs-on: ubuntu-latest
    needs: get-robots-version
    if:  ${{ needs.get-robots-version.outputs.modified == 'true' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      -
        name: Update robots version
        id: robots-update
        env:
          ROBOTS_VERSION: ${{ needs.get-robots-version.outputs.version }}
        run: |
          curl -Ls https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/${ROBOTS_VERSION}/robots.txt > ./layouts/robots.txt
          cat <<-EOF >>./layouts/robots.txt

          User-agent: *
          {{- if hugo.IsProduction | or (eq site.Params.env "production") }}
          Disallow:
          {{- else }}
          Disallow: /
          {{- end }}
          Sitemap: {{ "sitemap.xml" | absURL }}

          EOF
      -
        name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        env:
          ROBOTS_VERSION: ${{ needs.get-robots-version.outputs.version }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update robots to ${ROBOTS_VERSION}
          branch: ai-robots
          delete-branch: true
          title: '[ai-robots] Update to ${ROBOTS_VERSION}'
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          assignees: thespad
          draft: false